#!/usr/bin/env python3
"""Tally labels/*.md into RESULTS.md: label counts per requirement, split by
spec, agent and version, plus every requirement that wasn't Present."""
import collections
import pathlib
import re

root = pathlib.Path(__file__).resolve().parent.parent
LABELS = ["Present", "Wrong", "Partial", "Stub", "Omitted"]

runs = []
for path in sorted((root / "labels").glob("0*.md")):
    spec, version, agent, condition, run = path.stem.split("__")
    rows = re.findall(r"^\| ([EI]\d) \| (\w+) \| .*? \| (.*) \|$", path.read_text(), re.M)
    runs.append(dict(spec=spec, version=version, agent=agent, run=run, file=path.name,
                     labels={req: (label, note) for req, label, note in rows}))


def tally(group):
    c = collections.Counter(label for r in group for label, _ in r["labels"].values())
    return c


def row(name, group):
    c = tally(group)
    n = len(group)
    reqs = sum(c.values())
    return f"| {name} | {n} | {reqs} | " + " | ".join(str(c[l]) for l in LABELS) + " |"


out = ["# Results", "",
       "Generated by `scripts/summarize.py` from `labels/`. Counts are requirement labels: "
       "one per requirement per run (spec 01 has 8 requirements, spec 02 has 7).", ""]
head = "| Group | Runs | Requirements | " + " | ".join(LABELS) + " |\n|" + " --- |" * (3 + len(LABELS))

out += ["## By spec and agent", "", head]
for spec in sorted({r["spec"] for r in runs}):
    for agent in sorted({r["agent"] for r in runs}):
        g = [r for r in runs if r["spec"] == spec and r["agent"] == agent]
        if g:
            out.append(row(f"{spec}, {agent}", g))
out.append(row("**All**", runs))

out += ["", "## By version (all specs and agents)", "", head]
for version in sorted({r["version"] for r in runs}):
    out.append(row(version, [r for r in runs if r["version"] == version]))

out += ["", "## Explicit vs implied", "", "| Group | Labels | Present | Not present |", "| --- | --- | --- | --- |"]
for kind, prefix in (("Explicit (E)", "E"), ("Implied (I)", "I")):
    ls = [label for r in runs for req, (label, _) in r["labels"].items() if req.startswith(prefix)]
    out.append(f"| {kind} | {len(ls)} | {ls.count('Present')} | {len(ls) - ls.count('Present')} |")

out += ["", "## Requirements not Present", ""]
misses = [(r, req, label, note) for r in runs for req, (label, note) in r["labels"].items() if label != "Present"]
if misses:
    out += ["| Run | Requirement | Label | Note |", "| --- | --- | --- | --- |"]
    for r, req, label, note in misses:
        out.append(f"| [{r['file'][:-3]}](labels/{r['file']}) | {req} | {label} | {note} |")
else:
    out.append("None.")

(root / "RESULTS.md").write_text("\n".join(out) + "\n")
print("\n".join(out))
